"""initial schema

Revision ID: 761d2645e5ef
Revises: 
Create Date: 2026-03-05 09:10:19.846456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761d2645e5ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fault_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('symptoms', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('diagnosis_result', sa.Text(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onto_action_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_type_id', sa.Integer(), nullable=False),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onto_action_parameters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.String(), nullable=True),
    sa.Column('constraints_json', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onto_action_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_type_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('target_object_type_name', sa.String(), nullable=True),
    sa.Column('target_link_type_name', sa.String(), nullable=True),
    sa.Column('property_mappings_json', sa.Text(), nullable=True),
    sa.Column('condition_json', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onto_action_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('target_object_type_id', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=True),
    sa.Column('trigger_config_json', sa.Text(), nullable=True),
    sa.Column('exception_policy', sa.String(), nullable=True),
    sa.Column('exception_config_json', sa.Text(), nullable=True),
    sa.Column('validation_rules_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('onto_function_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('action_execution_id', sa.Integer(), nullable=True),
    sa.Column('input_data_json', sa.Text(), nullable=True),
    sa.Column('output_data_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onto_functions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('script_type', sa.String(), nullable=True),
    sa.Column('script_content', sa.Text(), nullable=True),
    sa.Column('input_schema_json', sa.Text(), nullable=True),
    sa.Column('output_schema_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('onto_link_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('source_object_type_id', sa.Integer(), nullable=False),
    sa.Column('target_object_type_id', sa.Integer(), nullable=False),
    sa.Column('cardinality', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('onto_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_type_id', sa.Integer(), nullable=False),
    sa.Column('source_object_id', sa.Integer(), nullable=False),
    sa.Column('target_object_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onto_object_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_key_property', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('onto_objects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_type_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('properties_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onto_properties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onto_properties')
    op.drop_table('onto_objects')
    op.drop_table('onto_object_types')
    op.drop_table('onto_links')
    op.drop_table('onto_link_types')
    op.drop_table('onto_functions')
    op.drop_table('onto_function_logs')
    op.drop_table('onto_action_types')
    op.drop_table('onto_action_rules')
    op.drop_table('onto_action_parameters')
    op.drop_table('onto_action_executions')
    op.drop_table('fault_records')
    op.drop_table('devices')
    # ### end Alembic commands ###
